### ISSUE TITLE
Error when accessing from another machine (LAN)

### ISSUE THREAD

**Issue by AlexisHutin** [Roy3838/Observer#5]
Hello,  
I encountered an issue when using Observer on my local network.

I’m running the application using Docker Compose on a machine in my local network. Here's the service definition:

```yaml
services:
  observer_app:
    image: observer:latest
    container_name: observer_app_and_proxy
    ports:
      - "3737:80"    # Web UI (Nginx)
      - "3838:3838"  # Proxy API (Python HTTPS)
    restart: unless-stopped
    environment:
      - OLLAMA_SERVICE_HOST=192.168.1.38
      - OLLAMA_SERVICE_PORT=11434
      - REACT_APP_DISABLE_AUTH=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

When trying to access the web interface from another machine on the same local network, I encounter the following errors:
The first step, access to the proxy on my_host_ip:3838, seems to be okay but when I reload I got : 
  ```
  Proxy error: <urlopen error [Errno -2] Name does not resolve>
  ```

And in the browser console of the UI I got this error:
  ```
  Uncaught Error: 
        auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/main/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.
  ```

Is there any way to run your project on another host in my local network ?
thx :)
